### PR TITLE
Exercise 25 -- SINR calculation options, SINR bar graph, Dev/Advanced mode feature, some bug fixes

### PR DESCRIPTION
**Pull request by mayurdhepe**
Addressed following issues for Exercise 25 --

SINR calculation options menu #31
Refactor SINR calculation code #32
Add SINR Bar graph #33
Add 2nd SINR model #34
Add menu options for Ideal filters with equal and unequal access bandwidths #35
Add Menu options to support 2 modes - Beginner and Advanced mode #36 
Bug -- center the rectangle around the PSD signal curve #37
Update the rectangle widths on PSD plot per the multiplier bandwidth #38

### CODE REVIEW

**Comment by mayurdhepe** [comment]
FYI, the review is only for the commit - 
https://github.com/vtwireless/HLSI/pull/42/commits/8960fd587e394b22af5fb82c7f3806331ea1f9b1
Exercise 25 -- SINR calculation options, SINR bar graph, Dev/Advanced mode feature, some bug fixes #42
All others were previous commits pending to be merged.

**Comment by carldietrich2** [comment]
Hello Mayur,

Thank you for checking regarding the updated Exercise 25 simulation.  I pulled the latest code and have two requested updates based on initial use of the simulation.

  *   The case in which filter bandwidths are all equal to the signal bandwidths should be an option “Ideal filter with bandwidth equal to signal bandwidth” in the “Select SINR calculation option” menu.
  *   In the case of ideal filters with equal excess bandwidth, SINR is not affected unless two or more signals overlap.  However, the expected behavior is that if a signal overlaps with the filter response of a receiver for a neighboring signal (shown by the semi-transparent rectangle), then the neighboring signal will experience interference and its SINR will be decreased.  However, in the screen shot below, SINR is not reduced for Comm Links 2 and 3.  Please ensure that the expected behavior occurs for all cases of filter bandwidth.  Specifically, interference should be calculated based on the interfering signal power that is within the filter bandwidth, rather than the interfering signal power within the bandwidth of the signal that is experiencing interference.

***@***.***

Please let me know when the updates have been made and pushed to the repository.

Thank you,
Carl

Carl Dietrich
Research Associate Professor, Wireless @ Virginia Tech
Bradley Department of Electrical and Computer Engineering
540-231-2963

**Comment by mayurdhepe** [comment]
Hello Professor,

Thank you for your suggestions/review comments on the code changes.
I have fixed the first point and added the case for "Ideal filter with bandwidth equal to signal bandwidth."
However, for the second point, I am unable to see the screenshot about which you have mentioned in the above comment. Although, I have made code updates as per the point -- "interference should be calculated based on the interfering signal power that is within the filter bandwidth".

We can also have a look at this issue in Monday's meeting, if it's not possible for you to add the screenshot here.

Thanks,
Mayur.

**Comment by carldietrich2** [comment]
Hello Mayur,

Thanks for the update and for letting me know that the screenshot was not visible in my previous email.  I have pasted the screenshot into the attached document.

Thank you,
Carl

Carl Dietrich
Research Associate Professor, Wireless @ Virginia Tech
Bradley Department of Electrical and Computer Engineering
540-231-2963

**Comment by mayurdhepe** [comment]
Hello Professor, 

Thank you for your reply. I have now fixed both the issues. For the 2nd one, while checking if 2 signals overlap or not, I have added a fix to consider the updated filter bandwidth (interferer's bandwidth * interferer's bandwidthMultiplier).
Also, while calculating the interferer power (ip), I am considering (interferer's bandwidth * interferer's bandwidthMultiplier).
You can find the code changes here: https://github.com/vtwireless/HLSI/pull/42/commits/0ddc22829068d6faa3cbba9210e3373b2aa7091a#diff-e541e8479b5b177f9bca4225a48eaeb808d1d2a10f36332841fcff59e60b639b

Also, this commit also includes fix for the Issue #39 Add enhancement for accepting URL params for mode.
Please let me know your thoughts.

Thank you,
Mayur.

**Comment by carldietrich2** [comment]
Hello Mayur,

Thank you for making the updates.

The interference should be a function of the signal bandwidth of the interfering signal (without its bandwidth multiplier), and the filter bandwidth of the receiver for the signal that is experiencing the interference (with its bandwidth multiplier).

That is because the filter that we are modeling would be used in the receiver.  For this simulation, we are assuming that the transmitted signals have very low power outside the intended signal bandwidths.  This corresponds closely to the way the signals are displayed.

Thank you,
Carl

Carl Dietrich
Research Associate Professor, Wireless @ Virginia Tech
Bradley Department of Electrical and Computer Engineering
540-231-2963

**Comment by mayurdhepe** [comment]
Added logic for SINR calculation in case of nonlinear front end model.

**Comment by mayurdhepe** [comment]
Hello Professor,

I have made the updates for fixing the capacity % values on Ex. 15 - 18 and included SINR bar graphs from Ex 19 to Ex 25.
Could you please test the updates so that I can merge them to master branch?

Thank you,
Mayur.

**Pull request merged**
